"""
Data models for the SMCA Arena system.
Defines structured data classes for agent responses, round results, 
combat outcomes, and overall SMCA results.
"""

from dataclasses import dataclass, field
from typing import List, Dict, Optional, Any
from datetime import datetime


@dataclass
class AgentResponse:
    """Response generated by a CombatAgent."""
    agent_name: str
    strategy: str
    text: str
    markers_used: List[int] = field(default_factory=list)
    marker_segments: List[str] = field(default_factory=list)
    similarities: List[float] = field(default_factory=list)
    confidence: float = 0.0
    generation_time: float = 0.0
    metadata: Dict[str, Any] = field(default_factory=dict)
    timestamp: str = field(default_factory=lambda: datetime.now().isoformat())

    def to_dict(self) -> Dict[str, Any]:
        return {
            'agent_name': self.agent_name,
            'strategy': self.strategy,
            'text': self.text,
            'markers_used': self.markers_used,
            'marker_segments': self.marker_segments,
            'similarities': self.similarities,
            'confidence': self.confidence,
            'generation_time': self.generation_time,
            'metadata': self.metadata,
            'timestamp': self.timestamp
        }


@dataclass
class RoundResult:
    """Result of a single combat round in the arena."""
    round_number: int
    standards_used: List[str]
    winner_name: str
    winner_score: float
    loser_name: str
    loser_score: float
    all_scores: Dict[str, float] = field(default_factory=dict)
    all_responses: List[AgentResponse] = field(default_factory=list)
    pressure_level: float = 0.0
    god_intervention: bool = False
    timestamp: str = field(default_factory=lambda: datetime.now().isoformat())

    def to_dict(self) -> Dict[str, Any]:
        return {
            'round_number': self.round_number,
            'standards_used': self.standards_used,
            'winner_name': self.winner_name,
            'winner_score': self.winner_score,
            'loser_name': self.loser_name,
            'loser_score': self.loser_score,
            'all_scores': self.all_scores,
            'all_responses': [r.to_dict() for r in self.all_responses],
            'pressure_level': self.pressure_level,
            'god_intervention': self.god_intervention,
            'timestamp': self.timestamp
        }


@dataclass
class CombatResult:
    """Complete result of an arena combat session."""
    query: str
    champion_name: str
    champion_response: Optional[AgentResponse] = None
    final_score: float = 0.0
    rounds: List[RoundResult] = field(default_factory=list)
    total_rounds: int = 0
    total_time: float = 0.0
    countdown_expired: bool = False
    god_interventions: int = 0
    metadata: Dict[str, Any] = field(default_factory=dict)
    timestamp: str = field(default_factory=lambda: datetime.now().isoformat())

    def to_dict(self) -> Dict[str, Any]:
        return {
            'query': self.query,
            'champion_name': self.champion_name,
            'champion_response': self.champion_response.to_dict() if self.champion_response else None,
            'final_score': self.final_score,
            'rounds': [r.to_dict() for r in self.rounds],
            'total_rounds': self.total_rounds,
            'total_time': self.total_time,
            'countdown_expired': self.countdown_expired,
            'god_interventions': self.god_interventions,
            'metadata': self.metadata,
            'timestamp': self.timestamp
        }


@dataclass
class SMCAResult:
    """Complete result of an SMCA query pipeline."""
    query: str
    final_answer: str
    champion_name: str
    combat_result: Optional[CombatResult] = None
    memory_stats: Dict[str, Any] = field(default_factory=dict)
    judge_confidence: float = 0.0
    base_judge_confidence: float = 0.0
    champion_resilience_score: float = 0.0
    standards_evolution: List[List[str]] = field(default_factory=list)
    god_was_consulted: bool = False
    total_processing_time: float = 0.0
    timestamp: str = field(default_factory=lambda: datetime.now().isoformat())

    def to_dict(self) -> Dict[str, Any]:
        return {
            'query': self.query,
            'final_answer': self.final_answer,
            'champion_name': self.champion_name,
            'combat_result': self.combat_result.to_dict() if self.combat_result else None,
            'memory_stats': self.memory_stats,
            'judge_confidence': self.judge_confidence,
            'base_judge_confidence': self.base_judge_confidence,
            'champion_resilience_score': self.champion_resilience_score,
            'standards_evolution': self.standards_evolution,
            'god_was_consulted': self.god_was_consulted,
            'total_processing_time': self.total_processing_time,
            'timestamp': self.timestamp
        }
